### ISSUE TITLE
Return Parameters

### ISSUE THREAD

**Issue by creichlin** [grow-graphics/gd#11]
When i create and register the following class:
```
type Test struct {
	gd.Class[Test, gd.Node]
}

func (r *Test) Test(gd.Context) {
	fmt.Println("Hello Test")
}

func (r *Test) Test2(context gd.Context, seed gd.Int) gd.String {
	fmt.Println("Hello Test 2", seed)
	return context.String("Test 2 Result")
}
```
I can instantiate the class and call the Test() method.
The Test2 method is not found though.

When i checked the source i saw that methods with a return parameter are implemented but disabled and when i enabled them  the method could be called from godot but it always returned an empty string.

Is that part still work in progress or is there another preferred way to return data back to godot?

**Comment by Splizard** [comment]
@creichlin thanks for reporting, I've enabled return values and fixed the issue for returning strings (and other Godot reference types). In the example project, GOARCH is now printed to the console by Godot which retrives this value as a `gd.String` from calling a Go method.

**Comment by creichlin** [comment]
Thanks for fixing it so fast! It works as expected now.
