### ISSUE TITLE
Errors when registering some gd classes

### ISSUE THREAD

**Issue by puzzir** [grow-graphics/gd#28]
When registering some gd classes, the Godot editor crashes with an error.  Error immediately after "Add Chid Node".

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x7ffe18757232]

goroutine 17 [running, locked to thread]:
grow.graphics/gd/gdextension.property_get_revert_func(0x4, 0x2bf1d47a9d0, 0xf20c7fd7b0)
        D:/Golang/GOPATH/pkg/mod/grow.graphics/gd@v0.0.0-20240613104355-8560ec89ebcd/gdextension/gdextension_interface.go:2456 +0x1a7
exit status 0xc0000005
```

Sample Code:

```go
package main

import (
	"grow.graphics/gd"
	"grow.graphics/gd/gdextension"
)

type NewObject struct {
	gd.Class[NewObject, gd.Button]
	//gd.Class[NewObject, gd.Label]
	//gd.Class[NewObject, gd.LinkButton]
	//gd.Class[NewObject, gd.TextEdit]
	//gd.Class[NewObject, gd.CodeEdit]
	//gd.Class[NewObject, gd.ItemList]
	//gd.Class[NewObject, gd.Panel]
}

func main() {
	godot, ok := gdextension.Link()
	if !ok {
		return
	}
	gd.Register[NewObject](godot)
}
```

**Comment by Splizard** [comment]
Thanks for reporting, I cannot reproduce this, what version of Godot are you using and what platform are you on>

**Comment by puzzir** [comment]
Godot v4.2.2.stable.official [15073afe3]
https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_win64.exe.zip

Microsoft Windows NT 10.0.19045.0

**Comment by devnull-twitch** [comment]
Can confirm this using 4.2.2 on Windows 11 with every gd.Control, gd.Button and Node3D the reported error occurs when adding it to the scene tree.
gd.Node and gd.Node2D work fine

**Comment by Splizard** [comment]
Thanks, have reproduced this and this is fixed.
