### ISSUE TITLE
change the name of the branch

### ISSUE THREAD

**Issue by pandak1d** [grow-graphics/gd#5]
You can change the name of the branch, otherwise it is difficult for others to find

**Comment by Splizard** [comment]
Have added this project to the Godot documentation page for GDExtension
https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/what_is_gdextension.html

In addition to this, the repo appears on the first page of Google results for:
"gdextension golang"
"godot 4.2 golang"
"godot golang bindings github"

I've made a couple of posts about the project on Reddit, this should also help people (who are interested) track down the project.

Although I understand the sentiment and concern, I think the project will be easy enough to find. I also think it's important for the project to develop an independent and standalone identity.
