### ISSUE TITLE
GDExtension support

### ISSUE THREAD

**Issue by TheoXD** [grow-graphics/gd#6]
This library appears to be developed with Alpha versions of the 4.0 branch back when it was still using GDNative.
Now that the API is stable, is there a chance to update this repo to make it work with the current master branch that uses GDExtension?

Also was c.go file generated or written by hand?
Thanks!

**Comment by Splizard** [comment]
Repo has been updated for 4.3, may walk this back to 4.2 stable as more things begin to work.
