### ISSUE TITLE
Building an apk

### ISSUE THREAD

**Issue by adcopeland** [grow-graphics/gd#60]
I was unable to build an apk without changing library.gdextension to have a "lib" prefix on the android library.
```
--- a/cmd/gd/graphics/library.gdextension
+++ b/cmd/gd/graphics/library.gdextension
@@ -11,4 +11,4 @@ linux.x86_64   = "linux_amd64.so"
 windows.x86_64 = "windows_amd64.dll"
 macos.x86_64   = "darwin_amd64.dylib"
 macos.arm64    = "darwin_arm64.dylib"
-android.arm64  = "android_arm64.so"
+android.arm64  = "libandroid_arm64.so"
```

This appears to be required to build an apk, packaging failed and said that the library must start with 'lib' when I tried without this change.

**Comment by Splizard** [comment]
Thank you very much for catching this!
