### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by alexatsu** [grow-graphics/gd#63]
I have issues replicating basic examples from the docs. What should i do?
Go 1.23
Godot 4.3
![image](https://github.com/user-attachments/assets/7c5c9cc2-947a-4524-a63e-44e5606dbeaf)

**Comment by Splizard** [comment]
What operating system and architecture are you on? Do you have cgo setup?

**Comment by alexatsu** [comment]
I'm stupid, sorry to bother! Everything on Linux installed rather easily but not on Windows.
I thought i installed msys2 and put the command correctly but it didn't install anything or i put it wrong.

**My specs:**
>Version	10.0.22631 Build 22631
Windows 11

**So with the second link to this, gcc intalled correctly and now it picking dgextension up:**
>Many people have good experiences with TDM-GCC: https://jmeubank.github.io/tdm-gcc/, https://github.com/jmeubank/tdm-gcc/releases

**Comment by Splizard** [comment]
Good to hear, we are keen to improve the Windows experience but we would need somebody on Windows who would like to contribute these improvements.
